// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.Kernel;
using uFrame.ECS;
using UniRx;


public partial class FlappingBirdsContext : ReactiveContext<FlappingBirds> {
    
    private int lastEntityId;
    
    private Bird _bird;
    
    private Flapping _flapping;
    
    public FlappingBirdsContext(uFrame.ECS.EcsSystem system) : 
            base(system) {
    }
    
    protected override System.Collections.Generic.IEnumerable<uFrame.ECS.IEcsComponentManager> GetSelectManagers() {
        yield return ComponentSystem.RegisterComponent<Bird>();
        yield return ComponentSystem.RegisterComponent<Flapping>();
        yield break;
    }
    
    public override bool Match(int entityId) {
        lastEntityId = entityId;
        if (!ComponentSystem.TryGetComponent(entityId, out _bird)) {
            return false;
        }
        if (!ComponentSystem.TryGetComponent(entityId, out _flapping)) {
            return false;
        }
        return true;
    }
    
    public override FlappingBirds Select() {
        var item = new FlappingBirds();;
        item.EntityId = lastEntityId;
        item.Bird = _bird;
        item.Flapping = _flapping;
        return item;
    }
}

public partial class FlappingBirds : uFrame.ECS.ContextItem {
    
    private Bird _Bird;
    
    private Flapping _Flapping;
    
    public Bird Bird {
        get {
            return _Bird;
        }
        set {
            _Bird = value;
        }
    }
    
    public Flapping Flapping {
        get {
            return _Flapping;
        }
        set {
            _Flapping = value;
        }
    }
    
    public int ComponentID {
        get {
            return 5;
        }
    }
}
