// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UniRx;
using uFrame.ECS;


public class RotaterBase : uFrame.ECS.EcsComponent {
}

public class SelectableBase : uFrame.ECS.EcsComponent {
}

public class PlayerBase : uFrame.ECS.EcsComponent {
}

public class DamageableBase : uFrame.ECS.EcsComponent {
}
