// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.Kernel;
using uFrame.ECS;
using UniRx;


public class RotaterSystemBase : uFrame.ECS.EcsSystem {
    
    private SelectablePlayersContext _SelectablePlayersContext;
    
    private RotatersContext _RotatersContext;
    
    private DamageablesContext _DamageablesContext;
    
    private IEcsComponentManagerOf<Rotater> _RotaterManager;
    
    private IEcsComponentManagerOf<Selectable> _SelectableManager;
    
    private IEcsComponentManagerOf<Player> _PlayerManager;
    
    private IEcsComponentManagerOf<Damageable> _DamageableManager;
    
    public SelectablePlayersContext SelectablePlayersContext {
        get {
            return _SelectablePlayersContext;
        }
        set {
            _SelectablePlayersContext = value;
        }
    }
    
    public RotatersContext RotatersContext {
        get {
            return _RotatersContext;
        }
        set {
            _RotatersContext = value;
        }
    }
    
    public DamageablesContext DamageablesContext {
        get {
            return _DamageablesContext;
        }
        set {
            _DamageablesContext = value;
        }
    }
    
    public IEcsComponentManagerOf<Rotater> RotaterManager {
        get {
            return _RotaterManager;
        }
        set {
            _RotaterManager = value;
        }
    }
    
    public IEcsComponentManagerOf<Selectable> SelectableManager {
        get {
            return _SelectableManager;
        }
        set {
            _SelectableManager = value;
        }
    }
    
    public IEcsComponentManagerOf<Player> PlayerManager {
        get {
            return _PlayerManager;
        }
        set {
            _PlayerManager = value;
        }
    }
    
    public IEcsComponentManagerOf<Damageable> DamageableManager {
        get {
            return _DamageableManager;
        }
        set {
            _DamageableManager = value;
        }
    }
    
    public override void Setup() {
        base.Setup();
        RotaterManager = ComponentSystem.RegisterComponent<Rotater>();
        SelectableManager = ComponentSystem.RegisterComponent<Selectable>();
        PlayerManager = ComponentSystem.RegisterComponent<Player>();
        DamageableManager = ComponentSystem.RegisterComponent<Damageable>();
        SelectablePlayersContext = new SelectablePlayersContext(this);
        RotatersContext = new RotatersContext(this);
        DamageablesContext = new DamageablesContext(this);
      
    }


    public void asdf(Context<object>[] contexts)
    {
        
    }
    protected void OnUpdateHandler(RotatersContextItem item) {
        // OnUpdate
        // Rotate
        this.Rotate();
    }
    
    protected virtual void Rotate() {
    }
    
    public void Update() {
        var e = RotatersContext.Items.GetEnumerator();
        for (
        ; e.MoveNext(); 
        ) {
            OnUpdateHandler(e.Current);
        }
    }
    
    protected void OnMouseDownHandler(SelectablePlayersContextItem entityidItem) {
        // OnMouseDown
        // MakeRotater
        this.MakeRotater();
    }
    
    protected virtual void MakeRotater() {
    }
    
    protected void OnCollisionEnterHandler(SelectablePlayersContextItem entityidItem, DamageablesContextItem collideridItem) {
        // OnCollisionEnter
        // Collided
        this.Collided();
    }
    
    protected virtual void Collided() {
    }
}
