// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.ECS {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    
    
    public class ComponentNodeDrawerBase : GenericNodeDrawer<ComponentNode,ComponentNodeViewModel> {
        
        public ComponentNodeDrawerBase(ComponentNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SystemNodeDrawerBase : GenericNodeDrawer<SystemNode,SystemNodeViewModel> {
        
        public SystemNodeDrawerBase(SystemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ItemTypesNodeDrawerBase : GenericNodeDrawer<ItemTypesNode,ItemTypesNodeViewModel> {
        
        public ItemTypesNodeDrawerBase(ItemTypesNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class EventNodeDrawerBase : GenericNodeDrawer<EventNode,EventNodeViewModel> {
        
        public EventNodeDrawerBase(EventNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class PublishNodeDrawerBase : GenericNodeDrawer<PublishNode,PublishNodeViewModel> {
        
        public PublishNodeDrawerBase(PublishNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class UserMethodNodeDrawerBase : GenericNodeDrawer<UserMethodNode,UserMethodNodeViewModel> {
        
        public UserMethodNodeDrawerBase(UserMethodNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ActionNodeDrawerBase : GenericNodeDrawer<ActionNode,ActionNodeViewModel> {
        
        public ActionNodeDrawerBase(ActionNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class HandlerNodeDrawerBase : GenericNodeDrawer<HandlerNode,HandlerNodeViewModel> {
        
        public HandlerNodeDrawerBase(HandlerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ComponentGroupNodeDrawerBase : GenericNodeDrawer<ComponentGroupNode,ComponentGroupNodeViewModel> {
        
        public ComponentGroupNodeDrawerBase(ComponentGroupNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class VariableNodeDrawerBase : GenericNodeDrawer<VariableNode,VariableNodeViewModel> {
        
        public VariableNodeDrawerBase(VariableNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ContextNodeDrawerBase : GenericNodeDrawer<ContextNode,ContextNodeViewModel> {
        
        public ContextNodeDrawerBase(ContextNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class TimerNodeDrawerBase : GenericNodeDrawer<TimerNode,TimerNodeViewModel> {
        
        public TimerNodeDrawerBase(TimerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StartTimerNodeDrawerBase : GenericNodeDrawer<StartTimerNode,StartTimerNodeViewModel> {
        
        public StartTimerNodeDrawerBase(StartTimerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StopTimerNodeDrawerBase : GenericNodeDrawer<StopTimerNode,StopTimerNodeViewModel> {
        
        public StopTimerNodeDrawerBase(StopTimerNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ComponentsNodeDrawerBase : GenericNodeDrawer<ComponentsNode,ComponentsNodeViewModel> {
        
        public ComponentsNodeDrawerBase(ComponentsNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class LiteralNodeDrawerBase : GenericNodeDrawer<LiteralNode,LiteralNodeViewModel> {
        
        public LiteralNodeDrawerBase(LiteralNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StringLiteralNodeDrawerBase : GenericNodeDrawer<StringLiteralNode,StringLiteralNodeViewModel> {
        
        public StringLiteralNodeDrawerBase(StringLiteralNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SequenceItemNodeDrawerBase : GenericNodeDrawer<SequenceItemNode,SequenceItemNodeViewModel> {
        
        public SequenceItemNodeDrawerBase(SequenceItemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class VariableReferenceNodeDrawerBase : GenericNodeDrawer<VariableReferenceNode,VariableReferenceNodeViewModel> {
        
        public VariableReferenceNodeDrawerBase(VariableReferenceNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class Vector3NodeDrawerBase : GenericNodeDrawer<Vector3Node,Vector3NodeViewModel> {
        
        public Vector3NodeDrawerBase(Vector3NodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class Vector2NodeDrawerBase : GenericNodeDrawer<Vector2Node,Vector2NodeViewModel> {
        
        public Vector2NodeDrawerBase(Vector2NodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class StringNodeDrawerBase : GenericNodeDrawer<StringNode,StringNodeViewModel> {
        
        public StringNodeDrawerBase(StringNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class BoolNodeDrawerBase : GenericNodeDrawer<BoolNode,BoolNodeViewModel> {
        
        public BoolNodeDrawerBase(BoolNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class FloatNodeDrawerBase : GenericNodeDrawer<FloatNode,FloatNodeViewModel> {
        
        public FloatNodeDrawerBase(FloatNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class IntNodeDrawerBase : GenericNodeDrawer<IntNode,IntNodeViewModel> {
        
        public IntNodeDrawerBase(IntNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ColorNodeDrawerBase : GenericNodeDrawer<ColorNode,ColorNodeViewModel> {
        
        public ColorNodeDrawerBase(ColorNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
}
