// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.ECS {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    
    
    public class ComponentNodeDrawerBase : GenericNodeDrawer<ComponentNode,ComponentNodeViewModel> {
        
        public ComponentNodeDrawerBase(ComponentNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class SystemNodeDrawerBase : GenericNodeDrawer<SystemNode,SystemNodeViewModel> {
        
        public SystemNodeDrawerBase(SystemNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class FilterNodeDrawerBase : GenericNodeDrawer<FilterNode,FilterNodeViewModel> {
        
        public FilterNodeDrawerBase(FilterNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class RequireAllNodeDrawerBase : GenericNodeDrawer<RequireAllNode,RequireAllNodeViewModel> {
        
        public RequireAllNodeDrawerBase(RequireAllNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class RequireOneNodeDrawerBase : GenericNodeDrawer<RequireOneNode,RequireOneNodeViewModel> {
        
        public RequireOneNodeDrawerBase(RequireOneNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ComponentFilterNodeDrawerBase : GenericNodeDrawer<ComponentFilterNode,ComponentFilterNodeViewModel> {
        
        public ComponentFilterNodeDrawerBase(ComponentFilterNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class ItemTypesNodeDrawerBase : GenericNodeDrawer<ItemTypesNode,ItemTypesNodeViewModel> {
        
        public ItemTypesNodeDrawerBase(ItemTypesNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class OnEventNodeDrawerBase : GenericNodeDrawer<OnEventNode,OnEventNodeViewModel> {
        
        public OnEventNodeDrawerBase(OnEventNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class PublishNodeDrawerBase : GenericNodeDrawer<PublishNode,PublishNodeViewModel> {
        
        public PublishNodeDrawerBase(PublishNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
    
    public class UserMethodNodeDrawerBase : GenericNodeDrawer<UserMethodNode,UserMethodNodeViewModel> {
        
        public UserMethodNodeDrawerBase(UserMethodNodeViewModel viewModel) : 
                base(viewModel) {
        }
    }
}
