// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.ECS {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    
    
    public class VariableBase : SingleInputSlot<IVariableConnectable> {
        
        public override string Name {
            get {
                return "Variable";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return false;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<Invert.Core.GraphDesigner.IGraphItem> GetAllowed() {
            return Repository.AllOf<IVariableConnectable>().OfType<IGraphItem>();;
        }
    }
    
    public partial interface IVariableConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class ValueBase : SingleInputSlot<IValueConnectable> {
        
        public override string Name {
            get {
                return "Value";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return false;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<Invert.Core.GraphDesigner.IGraphItem> GetAllowed() {
            return Repository.AllOf<IValueConnectable>().OfType<IGraphItem>();;
        }
    }
    
    public partial interface IValueConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class PropertyBase : SingleInputSlot<IPropertyConnectable> {
        
        public override string Name {
            get {
                return "Property";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return false;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return true;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<Invert.Core.GraphDesigner.IGraphItem> GetAllowed() {
            return Repository.AllOf<IPropertyConnectable>().OfType<IGraphItem>();;
        }
    }
    
    public partial interface IPropertyConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class TimerBase : SingleInputSlot<ITimerConnectable> {
        
        public override string Name {
            get {
                return "Timer";
            }
            set {
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return false;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return false;
            }
        }
        
        public override bool AllowSelection {
            get {
                return false;
            }
        }
        
        public override System.Collections.Generic.IEnumerable<Invert.Core.GraphDesigner.IGraphItem> GetAllowed() {
            return Repository.AllOf<ITimerConnectable>().OfType<IGraphItem>();;
        }
    }
    
    public partial interface ITimerConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
}
