// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using uFrame.Kernel;
using UnityEngine;


public class PlayTheGameHandler : object {
    
    public PlayButton EntityId;
    
    private uFrame.ECS.PointerClickDispatcher _Event;
    
    private uFrame.ECS.EcsSystem _System;
    
    private PublishStartPlayingAction bcdccadff = new PublishStartPlayingAction();
    
    public uFrame.ECS.PointerClickDispatcher Event {
        get {
            return _Event;
        }
        set {
            _Event = value;
        }
    }
    
    public uFrame.ECS.EcsSystem System {
        get {
            return _System;
        }
        set {
            _System = value;
        }
    }
    
    public virtual void Execute() {
        // Before visit PublishStartPlayingAction
        // Visit PublishStartPlayingAction
        bcdccadff.System = System;
        if (!bcdccadff.Execute()) {
            return;
        }
        // CALL EXECUTE ON PublishStartPlayingAction CLASS
        // HANDLER: PlayTheGame
    }
}

public class HideMenuHandler : object {
    
    public Menu Item;
    
    private StartPlaying _Event;
    
    private uFrame.ECS.EcsSystem _System;
    
    private UnityEngine.GameObject GameObjects_gameObject = default( UnityEngine.GameObject );
    
    private UnityEngine.MonoBehaviour GameObjects_behaviour = default( UnityEngine.MonoBehaviour );
    
    public StartPlaying Event {
        get {
            return _Event;
        }
        set {
            _Event = value;
        }
    }
    
    public uFrame.ECS.EcsSystem System {
        get {
            return _System;
        }
        set {
            _System = value;
        }
    }
    
    public virtual void Execute() {
        // Before visit uFrame.Actions.GameObjects.DeactiateGameObject
        GameObjects_behaviour = Item;
        // Visit uFrame.Actions.GameObjects.DeactiateGameObject
        uFrame.Actions.GameObjects.DeactiateGameObject(GameObjects_gameObject, GameObjects_behaviour);
        // HANDLER: HideMenu
    }
}

public class ShowMenuHandler : object {
    
    public Menu Item;
    
    private GameOver _Event;
    
    private uFrame.ECS.EcsSystem _System;
    
    private UnityEngine.GameObject GameObjects_gameObject = default( UnityEngine.GameObject );
    
    private UnityEngine.MonoBehaviour GameObjects_behaviour = default( UnityEngine.MonoBehaviour );
    
    public GameOver Event {
        get {
            return _Event;
        }
        set {
            _Event = value;
        }
    }
    
    public uFrame.ECS.EcsSystem System {
        get {
            return _System;
        }
        set {
            _System = value;
        }
    }
    
    public virtual void Execute() {
        // Before visit uFrame.Actions.GameObjects.ActivateGameObject
        GameObjects_behaviour = Item;
        // Visit uFrame.Actions.GameObjects.ActivateGameObject
        uFrame.Actions.GameObjects.ActivateGameObject(GameObjects_gameObject, GameObjects_behaviour);
        // HANDLER: ShowMenu
    }
}
